import json, os, subprocess, sys
import node_runner

HERE = "tools/oracle"
B = chr(92)

# (flags, pattern, unit, repeat, engines, note). The unit is repeated to
# build the subject.
#
# `engines:` is on every row, and which engines a row names is a fact about
# this library's limits rather than about ECMAScript - the *expectation* is
# still the oracle's. At default limits `max_backtrack` is 100,000, and a
# greedy loop over the subject pushes one entry per position, so both
# backtracking engines refuse a subject past about 100 KB. Only the Pike VM
# scales, so only the Pike VM is asked at the large sizes. Every pattern is
# also run at 64 KB, where all three answer and can be checked against each
# other; tests/data/vectors/ecmascript/long_limits.rxt asserts the ceiling
# itself.
ALL = "pike backtrack bitstate"
BIG = "pike"

ROWS = [
    ("u",  "^a+$",             "a",    65536, ALL, "64 KB, every engine"),
    ("u",  "^a+$",             "a",  1048576, BIG, "1 MB, the simplest scan"),
    ("u",  "^[a-z]+$",         "abc",  21845, ALL, "64 KB through a class"),
    ("u",  "^[a-z]+$",         "abc", 349525, BIG, "1 MB through a class"),
    ("u",  "^(?:ab)+$",        "ab",   32768, ALL, "64 KB of a repeated group"),
    ("u",  "^(?:ab)+$",        "ab",  262144, BIG, "512 KB of a repeated group"),
    ("u",  "^a+$",             "ab",  100000, BIG, "200 KB that must not match"),
    ("iu", "^[a-z]+$",         "AbC",  21845, ALL, "64 KB folded"),
    ("iu", "^[a-z]+$",         "AbC", 100000, BIG, "300 KB folded"),
    ("u",  "^" + B + "p{L}+$", B + "u{e9}",    262144, BIG, "512 KB of two-byte characters"),
    ("u",  "^" + B + "p{L}+$", B + "u{6f22}",  174762, BIG, "512 KB of three-byte characters"),
    # U+10400 is Lu; a regional indicator is astral and *not* a letter, which
    # tests the class rather than the length.
    ("u",  "^" + B + "p{L}+$", B + "u{10400}", 131072, BIG, "512 KB of astral letters"),
    ("u",  "^" + B + "p{L}+$", B + "u{1f1e6}", 131072, BIG, "512 KB of astral non-letters"),
    # No greedy loop over the subject, so the backtrackers do scale here and
    # are asked at the full length.
    ("u",  "[0-9]+",           "ab",  100000, ALL, "200 KB unanchored with no match"),
    ("u",  "^(?:[a-z]+,)+$",   "ab,", 100000, BIG, "300 KB with structure"),
]


def decode_unit(unit):
    """The unit as bytes, applying the same escapes the reader applies."""
    out = []
    i = 0
    while i < len(unit):
        if unit[i] == B and i + 1 < len(unit) and unit[i + 1] == "u":
            assert unit[i + 2] == "{"
            close = unit.index("}", i)
            out.append(chr(int(unit[i + 3:close], 16)))
            i = close + 1
            continue
        out.append(unit[i])
        i += 1
    return "".join(out)


def main():
    rows = []
    for flags, pattern, unit, repeat, _, _note in ROWS:
        rows.append((flags, pattern, decode_unit(unit) * repeat))

    finished = subprocess.run(
        node_runner.command(os.path.join(HERE, "node_match.mjs")),
        input=json.dumps([[f, p, s] for f, p, s in rows]),
        capture_output=True, text=True, check=True)
    answers = json.loads(finished.stdout)
    version = finished.stderr.strip().replace("\n", "; ")

    body = []
    for (flags, pattern, unit, repeat, engines, note), (_, _, subject), answer in zip(
            ROWS, rows, answers):
        if answer == "syntax":
            sys.stderr.write("node rejected /%s/%s\n" % (pattern, flags))
            return 1
        length = len(subject.encode("utf-8"))
        lines = ["# %s" % note,
                 "pattern: %s" % pattern,
                 "flags: %s" % flags,
                 "subject: %s" % unit,
                 "repeat: %d" % repeat,
                 "engines: %s" % engines]
        if answer is None:
            lines.append("expect: nomatch")
        else:
            spans = []
            for pair in answer:
                if pair is None:
                    spans.append("-")
                else:
                    start, end = pair
                    spans.append("%s-%s"
                                 % ("$" if start == length else start,
                                    "$" if end == length else end))
            lines.append("expect: %s" % " ".join(spans))
        body.append("\n".join(lines))

    path = "tests/data/vectors/ecmascript/long.rxt"
    with open(path, "w", encoding="utf-8", newline="\n") as out:
        out.write("# generated by tools/oracle/make_long_vectors.py\n")
        out.write("# oracle: %s\n" % version)
        out.write("# Long subjects. Every other vector file in this "
                  "directory is tens of\n")
        out.write("# bytes, which is the length at which a scanning bug does "
                  "not show: an\n")
        out.write("# off-by-one in a restart, a counter that only overflows "
                  "after a million\n")
        out.write("# steps, a memo sized from the wrong length. `repeat:` "
                  "builds the subject\n")
        out.write("# so that the record stays readable.\n")
        out.write("dialect: ecmascript\n")
        out.write("unicode: 17.0\n\n")
        out.write("\n\n".join(body))
        out.write("\n")
    sys.stderr.write("%s: %d records\n" % (path, len(body)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
