"""Which edition of the UCD the perl on PATH carries.

Two corpora here are generated by asking perl, and both make claims about
this number: `make_boundary_vectors.py` leaves rows out because perl has not
seen a rule yet, and `make_name_vectors.py` writes it into the header of what
it generates. Until 2026-09-24 neither asked - the number lived in prose
beside the code that depended on it, which is the shape that goes stale
without anything going red.

It lives in one module because there are two callers. A probe written twice
is a probe that will disagree with itself later; see the same argument in
`tools/oracle/vim_diff.py`, where one `VIM_COMMAND` exists so that a script
added later cannot be built without the setting the others have.
"""
import subprocess


def perl_ucd_version():
    """The UCD edition perl carries, or None if it cannot be asked.

    `Unicode::UCD::UnicodeVersion()` is perl's own answer, which is the point:
    it is read out of the interpreter that is about to answer the rows, not
    derived from its release number. The two travel together, but only one of
    them decides whether a disagreement can be a defect.
    """
    try:
        done = subprocess.run(["perl", "-MUnicode::UCD", "-e",
            "print Unicode::UCD::UnicodeVersion()"], capture_output=True,
            text=True, timeout=60)
    except (OSError, subprocess.TimeoutExpired):
        return None
    if done.returncode != 0:
        return None
    return done.stdout.strip() or None


def version_tuple(text):
    """`"15.1"` as a comparable tuple, padded so that 15.1 sorts above 15.0.0."""
    return tuple([int(part) for part in text.split(".")]
        + [0] * (3 - len(text.split("."))))
