/*
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * Copyright (C) 2026 Corey Pennycuff
 *
 * This file is part of Ghoti.io Regex.
 *
 * Ghoti.io Regex is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Ghoti.io Regex is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @file
 *
 * GENERATED by tools/unicode/gen_tables.py from UCD 17.0.0. Do not edit.
 *
 * Regenerate with:  tools/unicode/gen_tables.py
 * Verify with:      make check-unicode-tables
 */

#ifndef GHOTI_IO_GRX_SRC_UNICODE_TABLES_TABLES_INTERNAL_H
#define GHOTI_IO_GRX_SRC_UNICODE_TABLES_TABLES_INTERNAL_H

#include <ghoti.io/regex/macros.h>

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/** @brief The UCD release every table on this page was generated from. */
#define GRX_UCD_VERSION "17.0.0"

/** @brief What kind of thing a property record names. */
typedef enum {
  GRX_UPROP_BINARY = 0, ///< A binary property: `\p{Alphabetic}`.
  GRX_UPROP_GC,         ///< A General_Category value: `\p{gc=Lu}`, `\p{Lu}`.
  GRX_UPROP_SCRIPT,     ///< A Script value: `\p{sc=Greek}`.
  GRX_UPROP_SCX,        ///< A Script_Extensions value: `\p{scx=Greek}`.
  GRX_UPROP_NV,         ///< A Numeric_Value: `\p{nv=1/2}`.
  GRX_UPROP_KIND_COUNT  ///< Closes the enum; not a kind.
} GRX_UPropKind;

/**
 * @brief One Unicode property: its spelling, and how its set is reached.
 *
 * The code points are **not** here. They are ghoti.io-unicode's, asked for
 * by the name and kind below (see property.c), so that a `\p{...}` and a
 * `guni_set_contains()` in the same program cannot answer differently. What
 * a record holds is this library's own view of the property: the canonical
 * long name a dump prints, the kind that says which question to put to the
 * Unicode library, and `total`.
 *
 * `total` and `digest` are what is left of the ranges, and they are what
 * keeps the two readings of the UCD comparable now that only one of them is
 * stored. `total` is the figure a human can check against somebody else -
 * Node reports 1,886 code points in `\p{Lu}` for Unicode 17.0, and so does
 * this - and `digest` is the one that makes "the same set" mean the same
 * *members* rather than the same number of them. Both are the generator's,
 * derived from the UCD files without asking the library that answers, so
 * `Property.EverySetIsTheOneTheUCDFilesGive` compares two readings of one
 * release instead of comparing the generator with itself - which is what it
 * did while the ranges it summed and the total it summed them against both
 * came from the same run (documentation/unicode.md section 4).
 */
typedef struct GRX_UnicodeProperty {
  const char * name;  ///< The canonical long name.
  uint8_t kind;       ///< A @ref GRX_UPropKind.
  uint32_t total;     ///< Code points the property covers.
  uint64_t digest;    ///< FNV-1a 64 over the ranges the UCD files give it.
} GRX_UnicodeProperty;

/**
 * @brief One accepted spelling of a property or of a property's value.
 *
 * Sorted by name so that the strict resolver is a binary search; a second
 * table holds the same entries with UAX #44 loose spelling applied, for the
 * dialects that match loosely (documentation/unicode.md section 6).
 */
typedef struct GRX_UnicodeName {
  const char * name;  ///< The spelling.
  uint16_t kind;      ///< A @ref GRX_UPropKind.
  uint16_t property;  ///< Index into grx_unicode_properties.
} GRX_UnicodeName;

/** @brief One entry of a case-mapping table. */
typedef struct GRX_UnicodeCaseMap {
  uint32_t from; ///< The code point mapped.
  uint32_t to;   ///< What it maps to.
} GRX_UnicodeCaseMap;

/**
 * @brief One code point whose full case fold is more than one code point.
 *
 * Sorted by `code`, so a lookup is a binary search. The whole table is a
 * hundred and four entries, which is why the reverse question - *which* code
 * points fold to this sequence - is answered by a scan rather than by a
 * second index.
 */
typedef struct GRX_UnicodeFullFold {
  uint32_t code;   ///< The code point folded.
  uint32_t length; ///< Code points in `to`: 2 or 3.
  uint32_t to[3];  ///< The fold; entries past `length` are 0.
} GRX_UnicodeFullFold;

/**
 * @brief One code point's membership in a fold orbit.
 *
 * Every member of an orbit has an entry, so a lookup is one binary search
 * and the answer is a slice of the shared member array.
 */
typedef struct GRX_UnicodeOrbit {
  uint32_t code;  ///< The code point.
  uint32_t first; ///< Index of the orbit's first member.
  uint32_t count; ///< Members in the orbit, including `code` itself.
} GRX_UnicodeOrbit;

/** @brief One member of a property of strings: a slice of the point array. */
typedef struct GRX_UnicodeString {
  uint32_t first;  ///< Index of its first code point.
  uint32_t length; ///< Code points; 1 for a member that is a single one.
} GRX_UnicodeString;

/**
 * @brief A property of strings, as a slice of the shared sequence array.
 *
 * ECMAScript's `v` mode is the only thing that uses these. A property of
 * strings is not a character class: its members may be several code points
 * long, so it lowers to an alternation of literal sequences rather than to a
 * set (documentation/dialects.md section 8.4).
 *
 * `RGI_Emoji` is the union of the other six and its slice is the whole
 * array, so it costs three integers rather than a second copy.
 */
typedef struct GRX_UnicodeStringSet {
  const char * name; ///< Its one spelling; long and short names are equal.
  uint32_t first;    ///< Index of its first sequence.
  uint32_t count;    ///< Sequences in it.
} GRX_UnicodeStringSet;

/** Properties of strings: the flat code points, the sequences, the sets. */
extern const uint32_t grx_unicode_string_points[];
extern const size_t grx_unicode_string_point_count;

extern const GRX_UnicodeString grx_unicode_strings[];
extern const size_t grx_unicode_string_count;

extern const GRX_UnicodeStringSet grx_unicode_string_sets[];
extern const size_t grx_unicode_string_set_count;

extern const GRX_UnicodeProperty grx_unicode_properties[];
extern const size_t grx_unicode_property_count;

/**
 * @brief One Numeric_Value, as the reduced rational it is compared by.
 *
 * `\p{nv=...}` is the only property whose values are numbers rather than
 * names, so it does not appear in the spelling tables: UAX #44 section 5.9.2
 * says loose matching applies to property values "with the exception of
 * String Property values", and that for numeric values "numeric
 * equivalencies are applied" instead. `2/4`, `0.5` and `+1/2` are therefore
 * one value, while `-1/2` is a different one - which is why the ordinary
 * loose spelling, that drops `-` along with `_` and space, cannot be used
 * for these and a separate table exists.
 *
 * Sorted by (numerator, denominator). Every entry is reduced and so is
 * anything the parser produces, which makes equality an integer comparison
 * rather than a cross-multiplication.
 */
typedef struct GRX_UnicodeNumeric {
  int64_t numerator;   ///< Reduced, and carries the sign.
  int64_t denominator; ///< Reduced, and always positive.
  uint32_t property;   ///< Index into grx_unicode_properties.
} GRX_UnicodeNumeric;

extern const GRX_UnicodeNumeric grx_unicode_numeric_values[];
extern const size_t grx_unicode_numeric_value_count;

/** Property *names*: "gc", "General_Category", "sc", "scx". */
extern const GRX_UnicodeName grx_unicode_prop_names[];
extern const size_t grx_unicode_prop_name_count;

/** Property *values*, and the binary property names, by exact spelling. */
extern const GRX_UnicodeName grx_unicode_strict_names[];
extern const size_t grx_unicode_strict_name_count;

/** The same, with UAX #44 loose spelling applied and re-sorted. */
extern const GRX_UnicodeName grx_unicode_loose_names[];
extern const size_t grx_unicode_loose_name_count;

extern const GRX_UnicodeName grx_unicode_loose_prop_names[];
extern const size_t grx_unicode_loose_prop_name_count;

/**
 * Full case folding: CaseFolding.txt status F, the folds of more than one
 * code point.
 *
 * Only the code points whose full fold differs from their simple one are
 * here, so a full fold is this table's entry when it has one and
 * grx_unicode_fold_map's otherwise.
 */
extern const GRX_UnicodeFullFold grx_unicode_full_folds[];
extern const size_t grx_unicode_full_fold_count;

extern const GRX_UnicodeOrbit grx_unicode_fold_orbits[];
extern const size_t grx_unicode_fold_orbit_count;
extern const uint32_t grx_unicode_fold_orbit_members[];
extern const size_t grx_unicode_fold_orbit_member_count;

/** ECMA-262 Canonicalize without the `u` flag, and its orbits. */
extern const GRX_UnicodeCaseMap grx_unicode_es_legacy_map[];
extern const size_t grx_unicode_es_legacy_map_count;

extern const GRX_UnicodeOrbit grx_unicode_es_legacy_orbits[];
extern const size_t grx_unicode_es_legacy_orbit_count;
extern const uint32_t grx_unicode_es_legacy_orbit_members[];
extern const size_t grx_unicode_es_legacy_orbit_member_count;

/**
 * Simple_Uppercase_Mapping and Simple_Lowercase_Mapping.
 *
 * UnicodeData.txt fields 12 and 13, one code point to one code point and
 * absent where there is none. Neither a folding nor the ECMAScript
 * canonicalisation above: U+00DF has no simple uppercase, where its *full*
 * uppercase is "SS" and its fold shares an orbit with U+1E9E, and U+01F3
 * uppercases to U+01F1 rather than to the titlecase U+01F2. That is what a
 * replacement template asking for "the next character in upper case" means
 * - Vim's `\u` and `\U`.
 */


#ifdef __cplusplus
}
#endif

#endif // GHOTI_IO_GRX_SRC_UNICODE_TABLES_TABLES_INTERNAL_H
