/**
 * @file
 *
 * GENERATED by tools/unicode/gen_tables.py from UCD 17.0.0. Do not edit.
 *
 * Regenerate with:  tools/unicode/gen_tables.py
 * Verify with:      make check-unicode-tables
 *
 * Copyright 2026 by Corey Pennycuff
 */

#ifndef GHOTI_IO_GRX_SRC_UNICODE_TABLES_TABLES_INTERNAL_H
#define GHOTI_IO_GRX_SRC_UNICODE_TABLES_TABLES_INTERNAL_H

#include <ghoti.io/regex/macros.h>

#include <stddef.h>
#include <stdint.h>

#include "../../core/range_internal.h"

#ifdef __cplusplus
extern "C" {
#endif

/** @brief The UCD release every table on this page was generated from. */
#define GRX_UCD_VERSION "17.0.0"

/** @brief What kind of thing a property record names. */
typedef enum {
  GRX_UPROP_BINARY = 0, ///< A binary property: `\p{Alphabetic}`.
  GRX_UPROP_GC,         ///< A General_Category value: `\p{gc=Lu}`, `\p{Lu}`.
  GRX_UPROP_SCRIPT,     ///< A Script value: `\p{sc=Greek}`.
  GRX_UPROP_SCX,        ///< A Script_Extensions value: `\p{scx=Greek}`.
  GRX_UPROP_KIND_COUNT  ///< Closes the enum; not a kind.
} GRX_UPropKind;

/**
 * @brief One Unicode property, as a slice of the shared range array.
 *
 * `total` is the code-point count the UCD's own trailer states, carried
 * across so that a C test can check the table against the standard's
 * arithmetic rather than against the generator that produced it
 * (documentation/unicode.md section 4).
 */
typedef struct GRX_UnicodeProperty {
  const char * name;  ///< The canonical long name.
  uint8_t kind;       ///< A @ref GRX_UPropKind.
  uint32_t first;     ///< Index of the first range in grx_unicode_ranges.
  uint32_t count;     ///< Number of ranges.
  uint32_t total;     ///< Code points the property covers.
} GRX_UnicodeProperty;

/**
 * @brief One accepted spelling of a property or of a property's value.
 *
 * Sorted by name so that the strict resolver is a binary search; a second
 * table holds the same entries with UAX #44 loose spelling applied, for the
 * dialects that match loosely (documentation/unicode.md section 6).
 */
typedef struct GRX_UnicodeName {
  const char * name;  ///< The spelling.
  uint16_t kind;      ///< A @ref GRX_UPropKind.
  uint16_t property;  ///< Index into grx_unicode_properties.
} GRX_UnicodeName;

/** @brief One entry of a case-mapping table. */
typedef struct GRX_UnicodeCaseMap {
  uint32_t from; ///< The code point mapped.
  uint32_t to;   ///< What it maps to.
} GRX_UnicodeCaseMap;

/**
 * @brief One code point's membership in a fold orbit.
 *
 * Every member of an orbit has an entry, so a lookup is one binary search
 * and the answer is a slice of the shared member array.
 */
typedef struct GRX_UnicodeOrbit {
  uint32_t code;  ///< The code point.
  uint32_t first; ///< Index of the orbit's first member.
  uint32_t count; ///< Members in the orbit, including `code` itself.
} GRX_UnicodeOrbit;

/** @brief One member of a property of strings: a slice of the point array. */
typedef struct GRX_UnicodeString {
  uint32_t first;  ///< Index of its first code point.
  uint32_t length; ///< Code points; 1 for a member that is a single one.
} GRX_UnicodeString;

/**
 * @brief A property of strings, as a slice of the shared sequence array.
 *
 * ECMAScript's `v` mode is the only thing that uses these. A property of
 * strings is not a character class: its members may be several code points
 * long, so it lowers to an alternation of literal sequences rather than to a
 * set (documentation/dialects.md section 8.4).
 *
 * `RGI_Emoji` is the union of the other six and its slice is the whole
 * array, so it costs three integers rather than a second copy.
 */
typedef struct GRX_UnicodeStringSet {
  const char * name; ///< Its one spelling; long and short names are equal.
  uint32_t first;    ///< Index of its first sequence.
  uint32_t count;    ///< Sequences in it.
} GRX_UnicodeStringSet;

extern const GRX_CharRange grx_unicode_ranges[];
extern const size_t grx_unicode_range_count;

/** Properties of strings: the flat code points, the sequences, the sets. */
extern const uint32_t grx_unicode_string_points[];
extern const size_t grx_unicode_string_point_count;

extern const GRX_UnicodeString grx_unicode_strings[];
extern const size_t grx_unicode_string_count;

extern const GRX_UnicodeStringSet grx_unicode_string_sets[];
extern const size_t grx_unicode_string_set_count;

extern const GRX_UnicodeProperty grx_unicode_properties[];
extern const size_t grx_unicode_property_count;

/** Property *names*: "gc", "General_Category", "sc", "scx". */
extern const GRX_UnicodeName grx_unicode_prop_names[];
extern const size_t grx_unicode_prop_name_count;

/** Property *values*, and the binary property names, by exact spelling. */
extern const GRX_UnicodeName grx_unicode_strict_names[];
extern const size_t grx_unicode_strict_name_count;

/** The same, with UAX #44 loose spelling applied and re-sorted. */
extern const GRX_UnicodeName grx_unicode_loose_names[];
extern const size_t grx_unicode_loose_name_count;

extern const GRX_UnicodeName grx_unicode_loose_prop_names[];
extern const size_t grx_unicode_loose_prop_name_count;

/** Simple case folding: CaseFolding.txt statuses C and S. */
extern const GRX_UnicodeCaseMap grx_unicode_fold_map[];
extern const size_t grx_unicode_fold_map_count;

extern const GRX_UnicodeOrbit grx_unicode_fold_orbits[];
extern const size_t grx_unicode_fold_orbit_count;
extern const uint32_t grx_unicode_fold_orbit_members[];
extern const size_t grx_unicode_fold_orbit_member_count;

/** ECMA-262 Canonicalize without the `u` flag, and its orbits. */
extern const GRX_UnicodeCaseMap grx_unicode_es_legacy_map[];
extern const size_t grx_unicode_es_legacy_map_count;

extern const GRX_UnicodeOrbit grx_unicode_es_legacy_orbits[];
extern const size_t grx_unicode_es_legacy_orbit_count;
extern const uint32_t grx_unicode_es_legacy_orbit_members[];
extern const size_t grx_unicode_es_legacy_orbit_member_count;

#ifdef __cplusplus
}
#endif

#endif // GHOTI_IO_GRX_SRC_UNICODE_TABLES_TABLES_INTERNAL_H
