/*
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * Copyright (C) 2026 Corey Pennycuff
 *
 * This file is part of Ghoti.io Regex.
 *
 * Ghoti.io Regex is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Ghoti.io Regex is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @file
 *
 * GENERATED by tools/unicode/gen_tables.py from UCD 17.0.0. Do not edit.
 *
 * Regenerate with:  tools/unicode/gen_tables.py
 * Verify with:      make check-unicode-tables
 */

#ifndef GHOTI_IO_GRX_SRC_UNICODE_TABLES_TABLES_INTERNAL_H
#define GHOTI_IO_GRX_SRC_UNICODE_TABLES_TABLES_INTERNAL_H

#include <ghoti.io/regex/macros.h>

#include <stddef.h>
#include <stdint.h>

#include "../../core/range_internal.h"

#ifdef __cplusplus
extern "C" {
#endif

/** @brief The UCD release every table on this page was generated from. */
#define GRX_UCD_VERSION "17.0.0"

/** @brief What kind of thing a property record names. */
typedef enum {
  GRX_UPROP_BINARY = 0, ///< A binary property: `\p{Alphabetic}`.
  GRX_UPROP_GC,         ///< A General_Category value: `\p{gc=Lu}`, `\p{Lu}`.
  GRX_UPROP_SCRIPT,     ///< A Script value: `\p{sc=Greek}`.
  GRX_UPROP_SCX,        ///< A Script_Extensions value: `\p{scx=Greek}`.
  GRX_UPROP_NV,         ///< A Numeric_Value: `\p{nv=1/2}`.
  GRX_UPROP_KIND_COUNT  ///< Closes the enum; not a kind.
} GRX_UPropKind;

/**
 * @brief One Unicode property, as a slice of the shared range array.
 *
 * `total` is the code-point count the UCD's own trailer states, carried
 * across so that a C test can check the table against the standard's
 * arithmetic rather than against the generator that produced it
 * (documentation/unicode.md section 4).
 */
typedef struct GRX_UnicodeProperty {
  const char * name;  ///< The canonical long name.
  uint8_t kind;       ///< A @ref GRX_UPropKind.
  uint32_t first;     ///< Index of the first range in grx_unicode_ranges.
  uint32_t count;     ///< Number of ranges.
  uint32_t total;     ///< Code points the property covers.
} GRX_UnicodeProperty;

/**
 * @brief One accepted spelling of a property or of a property's value.
 *
 * Sorted by name so that the strict resolver is a binary search; a second
 * table holds the same entries with UAX #44 loose spelling applied, for the
 * dialects that match loosely (documentation/unicode.md section 6).
 */
typedef struct GRX_UnicodeName {
  const char * name;  ///< The spelling.
  uint16_t kind;      ///< A @ref GRX_UPropKind.
  uint16_t property;  ///< Index into grx_unicode_properties.
} GRX_UnicodeName;

/**
 * @brief One run of code points sharing a break property value.
 *
 * Sorted by `low` and non-overlapping, so a lookup is a binary search. Only
 * the runs a UCD file lists are here; a code point in none of them has the
 * property's default, which is value 0 in every one of these tables - Other
 * for the UAX #29 properties, XX for line breaking, None for
 * Indic_Conjunct_Break.
 */
typedef struct GRX_UnicodeBreakRange {
  uint32_t low;   ///< First code point of the run.
  uint32_t high;  ///< Last code point of the run.
  uint32_t value; ///< The property value, as the matching enum numbers it.
} GRX_UnicodeBreakRange;

/** @brief One entry of a case-mapping table. */
typedef struct GRX_UnicodeCaseMap {
  uint32_t from; ///< The code point mapped.
  uint32_t to;   ///< What it maps to.
} GRX_UnicodeCaseMap;

/**
 * @brief One code point whose full case fold is more than one code point.
 *
 * Sorted by `code`, so a lookup is a binary search. The whole table is a
 * hundred and four entries, which is why the reverse question - *which* code
 * points fold to this sequence - is answered by a scan rather than by a
 * second index.
 */
typedef struct GRX_UnicodeFullFold {
  uint32_t code;   ///< The code point folded.
  uint32_t length; ///< Code points in `to`: 2 or 3.
  uint32_t to[3];  ///< The fold; entries past `length` are 0.
} GRX_UnicodeFullFold;

/**
 * @brief One code point's membership in a fold orbit.
 *
 * Every member of an orbit has an entry, so a lookup is one binary search
 * and the answer is a slice of the shared member array.
 */
typedef struct GRX_UnicodeOrbit {
  uint32_t code;  ///< The code point.
  uint32_t first; ///< Index of the orbit's first member.
  uint32_t count; ///< Members in the orbit, including `code` itself.
} GRX_UnicodeOrbit;

/** @brief One member of a property of strings: a slice of the point array. */
typedef struct GRX_UnicodeString {
  uint32_t first;  ///< Index of its first code point.
  uint32_t length; ///< Code points; 1 for a member that is a single one.
} GRX_UnicodeString;

/**
 * @brief A property of strings, as a slice of the shared sequence array.
 *
 * ECMAScript's `v` mode is the only thing that uses these. A property of
 * strings is not a character class: its members may be several code points
 * long, so it lowers to an alternation of literal sequences rather than to a
 * set (documentation/dialects.md section 8.4).
 *
 * `RGI_Emoji` is the union of the other six and its slice is the whole
 * array, so it costs three integers rather than a second copy.
 */
typedef struct GRX_UnicodeStringSet {
  const char * name; ///< Its one spelling; long and short names are equal.
  uint32_t first;    ///< Index of its first sequence.
  uint32_t count;    ///< Sequences in it.
} GRX_UnicodeStringSet;

extern const GRX_CharRange grx_unicode_ranges[];
extern const size_t grx_unicode_range_count;

/** Properties of strings: the flat code points, the sequences, the sets. */
extern const uint32_t grx_unicode_string_points[];
extern const size_t grx_unicode_string_point_count;

extern const GRX_UnicodeString grx_unicode_strings[];
extern const size_t grx_unicode_string_count;

extern const GRX_UnicodeStringSet grx_unicode_string_sets[];
extern const size_t grx_unicode_string_set_count;

extern const GRX_UnicodeProperty grx_unicode_properties[];
extern const size_t grx_unicode_property_count;

/**
 * @brief One Numeric_Value, as the reduced rational it is compared by.
 *
 * `\p{nv=...}` is the only property whose values are numbers rather than
 * names, so it does not appear in the spelling tables: UAX #44 section 5.9.2
 * says loose matching applies to property values "with the exception of
 * String Property values", and that for numeric values "numeric
 * equivalencies are applied" instead. `2/4`, `0.5` and `+1/2` are therefore
 * one value, while `-1/2` is a different one - which is why the ordinary
 * loose spelling, that drops `-` along with `_` and space, cannot be used
 * for these and a separate table exists.
 *
 * Sorted by (numerator, denominator). Every entry is reduced and so is
 * anything the parser produces, which makes equality an integer comparison
 * rather than a cross-multiplication.
 */
typedef struct GRX_UnicodeNumeric {
  int64_t numerator;   ///< Reduced, and carries the sign.
  int64_t denominator; ///< Reduced, and always positive.
  uint32_t property;   ///< Index into grx_unicode_properties.
} GRX_UnicodeNumeric;

extern const GRX_UnicodeNumeric grx_unicode_numeric_values[];
extern const size_t grx_unicode_numeric_value_count;

/** Property *names*: "gc", "General_Category", "sc", "scx". */
extern const GRX_UnicodeName grx_unicode_prop_names[];
extern const size_t grx_unicode_prop_name_count;

/** Property *values*, and the binary property names, by exact spelling. */
extern const GRX_UnicodeName grx_unicode_strict_names[];
extern const size_t grx_unicode_strict_name_count;

/** The same, with UAX #44 loose spelling applied and re-sorted. */
extern const GRX_UnicodeName grx_unicode_loose_names[];
extern const size_t grx_unicode_loose_name_count;

extern const GRX_UnicodeName grx_unicode_loose_prop_names[];
extern const size_t grx_unicode_loose_prop_name_count;

/**
 * The break properties: UAX #29's three, UAX #14's one, and the
 * Indic_Conjunct_Break that UAX #29's GB9c needs.
 */
extern const GRX_UnicodeBreakRange grx_unicode_gcb_ranges[];
extern const size_t grx_unicode_gcb_range_count;
extern const GRX_UnicodeBreakRange grx_unicode_wb_ranges[];
extern const size_t grx_unicode_wb_range_count;
extern const GRX_UnicodeBreakRange grx_unicode_sb_ranges[];
extern const size_t grx_unicode_sb_range_count;
extern const GRX_UnicodeBreakRange grx_unicode_lb_ranges[];
extern const size_t grx_unicode_lb_range_count;
extern const GRX_UnicodeBreakRange grx_unicode_incb_ranges[];
extern const size_t grx_unicode_incb_range_count;
extern const GRX_UnicodeBreakRange grx_unicode_extpict_ranges[];
extern const size_t grx_unicode_extpict_range_count;
extern const GRX_UnicodeBreakRange grx_unicode_ea_ranges[];
extern const size_t grx_unicode_ea_range_count;
extern const GRX_UnicodeBreakRange grx_unicode_epcn_ranges[];
extern const size_t grx_unicode_epcn_range_count;

/** Simple case folding: CaseFolding.txt statuses C and S. */
extern const GRX_UnicodeCaseMap grx_unicode_fold_map[];
extern const size_t grx_unicode_fold_map_count;

/**
 * Full case folding: CaseFolding.txt status F, the folds of more than one
 * code point.
 *
 * Only the code points whose full fold differs from their simple one are
 * here, so a full fold is this table's entry when it has one and
 * grx_unicode_fold_map's otherwise.
 */
extern const GRX_UnicodeFullFold grx_unicode_full_folds[];
extern const size_t grx_unicode_full_fold_count;

extern const GRX_UnicodeOrbit grx_unicode_fold_orbits[];
extern const size_t grx_unicode_fold_orbit_count;
extern const uint32_t grx_unicode_fold_orbit_members[];
extern const size_t grx_unicode_fold_orbit_member_count;

/** ECMA-262 Canonicalize without the `u` flag, and its orbits. */
extern const GRX_UnicodeCaseMap grx_unicode_es_legacy_map[];
extern const size_t grx_unicode_es_legacy_map_count;

extern const GRX_UnicodeOrbit grx_unicode_es_legacy_orbits[];
extern const size_t grx_unicode_es_legacy_orbit_count;
extern const uint32_t grx_unicode_es_legacy_orbit_members[];
extern const size_t grx_unicode_es_legacy_orbit_member_count;

/**
 * Simple_Uppercase_Mapping and Simple_Lowercase_Mapping.
 *
 * UnicodeData.txt fields 12 and 13, one code point to one code point and
 * absent where there is none. Neither a folding nor the ECMAScript
 * canonicalisation above: U+00DF has no simple uppercase, where its *full*
 * uppercase is "SS" and its fold shares an orbit with U+1E9E, and U+01F3
 * uppercases to U+01F1 rather than to the titlecase U+01F2. That is what a
 * replacement template asking for "the next character in upper case" means
 * - Vim's `\u` and `\U`.
 */
extern const GRX_UnicodeCaseMap grx_unicode_simple_upper_map[];
extern const size_t grx_unicode_simple_upper_map_count;
extern const GRX_UnicodeCaseMap grx_unicode_simple_lower_map[];
extern const size_t grx_unicode_simple_lower_map_count;

/** Character names for `\N{NAME}`: the word dictionary, then the names.
 *
 * A name is a run of tokens in `grx_unicode_name_tokens`, from its entry in
 * `grx_unicode_name_offset` to the next; each token is a word number into
 * the dictionary in its low 15 bits, with bit 15 set when a `-` rather than
 * a space precedes it. The rows are sorted by name so that a lookup can
 * binary search them.
 */
extern const char grx_unicode_name_words[];
extern const uint32_t grx_unicode_name_word_offset[];
extern const size_t grx_unicode_name_word_count;

/** A family whose names are computed from the code point. */
typedef struct {
  uint32_t first;        /**< First code point. */
  uint32_t last;         /**< Last code point. */
  const char * prefix;   /**< What every name in it begins with. */
  uint8_t hangul;        /**< 1 when the tail is a jamo spelling, not hex. */
} GRX_UnicodeNameRange;

extern const GRX_UnicodeNameRange grx_unicode_name_ranges[];
extern const size_t grx_unicode_name_range_count;

extern const uint16_t grx_unicode_name_tokens[];
extern const uint32_t grx_unicode_name_offset[];
extern const uint32_t grx_unicode_name_codepoint[];
extern const size_t grx_unicode_name_count;

/**
 * @brief The Script_Extensions set of every code point, as a bitmap.
 *
 * One row per distinct set, `grx_unicode_script_set_words` words of 64 bits
 * each, and `grx_unicode_script_ranges` says which row a code point takes -
 * sorted and non-overlapping, so the lookup is a binary search and the
 * `value` field is the row index rather than a property value.
 *
 * The sets carry UTS #39 section 5.1's **augmentation** already applied:
 * Han also names Japanese, Korean and HanBopomofo; Hiragana and Katakana
 * also name Japanese; Hangul also names Korean; Bopomofo also names
 * HanBopomofo. Those three are virtual scripts that exist nowhere in the
 * UCD and are appended after every real one, so a script's id still means
 * what it meant. With them applied per character, the whole of the script
 * run rule is one set intersection.
 *
 * Three set indices are named because the rule names them: a character
 * whose set is exactly Inherited is always accepted, one whose set is
 * exactly Common is accepted subject to the digit rule, and one whose set
 * is exactly Unknown can only appear in a run shorter than two characters.
 */
#define GRX_UNICODE_SCRIPT_WORDS 3
extern const uint64_t grx_unicode_script_sets[][GRX_UNICODE_SCRIPT_WORDS];
extern const size_t grx_unicode_script_set_count;
extern const size_t grx_unicode_script_set_words;
extern const GRX_UnicodeBreakRange grx_unicode_script_ranges[];
extern const size_t grx_unicode_script_range_count;
extern const size_t grx_unicode_script_set_common;
extern const size_t grx_unicode_script_set_inherited;
extern const size_t grx_unicode_script_set_unknown;

/**
 * @brief The first code point of each block of ten decimal digits.
 *
 * A script run's digits must all come from one set of ten adjacent
 * characters, so what the check needs is each set's zero. The generator
 * asserts that every Nd code point sits in a block of exactly ten whose
 * numeric values run 0 to 9, which is what makes a single sorted array
 * enough.
 */
extern const uint32_t grx_unicode_digit_zeros[];
extern const size_t grx_unicode_digit_zero_count;

#ifdef __cplusplus
}
#endif

#endif // GHOTI_IO_GRX_SRC_UNICODE_TABLES_TABLES_INTERNAL_H
